Repository pisign/pisign-backend, pull requests merged in 2020-02, with the labels that each got.

#32 Config actions
  api/README.md
  api/clock/api.go
  api/factory.go
  api/weather/api.go
  api/weather/weather_test.go
  go.mod
  go.sum
  pool/pool.go
  server/server.go
  socket/socket.go
  types/api.go
  types/config.go
  types/interfaces.go
Labels: structural

#35 Deletion fixes
  api/README.md
  api/clock/api.go
  api/factory.go
  api/unmarshal.go
  api/weather/api.go
  api/weather/weather_test.go
  exampleClients/widgets.html
  pool/pool.go
  server/server.go
  socket/socket.go
  types/api.go
  types/config.go
  types/interfaces.go
Labels: structural

#39 [API] clock api returns unix timestamp instead of string
  api/clock/api.go
  spec/specfile
  types/clock.go
Labels: frontend compatibility

#38 [TESTS] additional tests + GoMock example
  api/weather/types.go
  api/weather/weather_test.go
  mocks/mock_api.go
  server/server.go
  utils/utils.go
  utils/utils_test.go
Labels: testing

#42 updated go server to be able to host the vue files, updated gitignore…
  .gitignore
  server/server.go
Labels: frontend compatibility, structural

#43 Trying to fix infinite cpu usage bug
  api/clock/api.go
  api/weather/api.go
  types/api.go
  types/interfaces.go
Labels: bug
