Repository pisign/pisign-backend, pull requests merged in 2020-03, with the labels that each got.

#51 Position info is now auto send with Response data
  socket/socket.go
  types/api.go
  types/interfaces.go
  types/message.go
Labels: enhancement, frontend compatibility

#52 On an api switch, the server now checks the `name` of the new API before removing the exiting API
  api/factory.go
  pool/pool.go
Labels: bug

#53 configs are sent with responses (original commit)
  api/clock/api.go
  api/slideshow/api.go
  api/weather/api.go
  spec/specfile
  types/clock.go
  types/slideshow.go
  types/weather.go
Labels: enhancement, frontend compatibility

#60 fixing twitter cache bug
  api/weather/api.go
Labels: bug, frontend compatibility
